# DataSource Config
spring.datasource:
  url: jdbc:mysql://152.136.209.249:3306/learningpass?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  username: root
  password: ljj13757335326
  driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    connection-timeout: 600000 #最大超时时间
    maximum-pool-size: 500 #连接数
    max-lifetime: 1800000 #控制池中连接的最大生存期
    minimum-idle: 20 #此属性控制 HikariCP尝试在池中维护的最小空闲连接数
    validation-timeout: 3000 #此属性控制测试连接是否活跃的最长时间。此值必须小于 connectionTimeout
    idle-timeout: 60000 #此属性控制允许连接在池中处于空闲状态的最长时间

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
#  #mybatis-plus配置控制台打印完整带参数SQL语句
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081


dun:
  jwt:
    #    加密密钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    #      token有效时长，7天
    expire: 5000
    #expire: 604800
    header: Authorization

